version: '3.8'

services:

  # RabbitMQ Service
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "15672:15672"  # RabbitMQ Management UI
      - "5672:5672"    # Default RabbitMQ port
    networks:
      - microservices-net

  # ----------------------------
  # SQL Server for UserService
  # ----------------------------
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    networks:
      - microservices-net
    volumes:
      - sqlserverdata:/var/opt/mssql

  # ----------------------------
  # MongoDB for TaskService
  # ----------------------------
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - microservices-net
    volumes:
      - mongodata:/data/db

  # ----------------------------
  # User Service (EF Core)
  # ----------------------------
  userservice:
    container_name: UserService
    build:
      context: .
      dockerfile: Services/UserService/UserService.API/Dockerfile
    ports:
      - "5260:8080"
    depends_on:
      - sqlserver
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=UserDb;User=sa;Password=YourStrong!Password123;TrustServerCertificate=True;
    networks:
      - microservices-net

  # ----------------------------
  # Task Service (MongoDB)
  # ----------------------------
  taskservice:
    container_name: TaskService
    build:
      context: .
      dockerfile: Services/TaskService/TaskService.API/Dockerfile
    ports:
      - "5214:8080"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoSettings__ConnectionString=mongodb://root:example@mongodb:27017
      - MongoSettings__Database=TodoTaskDb
    networks:
      - microservices-net

# ----------------------------
# Networks & Volumes
# ----------------------------
networks:
  microservices-net:
    driver: bridge

volumes:
  sqlserverdata:
  mongodata:
